"""empty message

Revision ID: 034deecb08b3
Revises: 
Create Date: 2022-08-26 18:58:50.927523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034deecb08b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('breed', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat')
    # ### end Alembic commands ###
