"""empty message

Revision ID: 438114235ba4
Revises: add2a4affa2e
Create Date: 2022-09-01 22:40:58.038399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438114235ba4'
down_revision = 'add2a4affa2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'int_age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('int_age', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
