"""empty message

Revision ID: 6245a47424ea
Revises: 438114235ba4
Create Date: 2022-09-01 22:42:30.863968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6245a47424ea'
down_revision = '438114235ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('ages', sa.Integer(), nullable=True))
    op.drop_column('cat', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('age', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('cat', 'ages')
    # ### end Alembic commands ###
