"""empty message

Revision ID: add2a4affa2e
Revises: 034deecb08b3
Create Date: 2022-08-27 16:13:12.085909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add2a4affa2e'
down_revision = '034deecb08b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('int_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'int_age')
    # ### end Alembic commands ###
